package main

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path"
	"strings"
	"time"
)

// checksumVerificationRequired controls how a MISSING SHA256SUMS asset is
// treated. Releases published before checksums existed have none, so requiring
// it outright would strand every current install on an old version. Flip this
// to true once the first checksummed release is out; a digest MISMATCH is
// always fatal regardless of this setting.
const checksumVerificationRequired = false

// checksumFileName is the release asset holding the SHA-256 digests of every
// published artifact. It is generated by .github/workflows/build.yml and
// published alongside the binaries.
const checksumFileName = "SHA256SUMS"

// checksumHTTPTransport lets tests serve SHA256SUMS in-process. Nil means the
// default transport.
var checksumHTTPTransport http.RoundTripper

// parseChecksumFile extracts the digest for wantName from a SHA256SUMS body.
// Both the GNU coreutils format ("<hex>  <name>") and the BSD shasum format
// ("SHA256 (<name>) = <hex>") are accepted, so the file can be produced on any
// build host. A leading "*" (binary mode) is stripped from the name.
func parseChecksumFile(content, wantName string) (string, error) {
	scanner := bufio.NewScanner(strings.NewReader(content))
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		var hexSum, name string
		if strings.HasPrefix(line, "SHA256 (") {
			// BSD: SHA256 (name) = hex
			end := strings.Index(line, ") = ")
			if end < 0 {
				continue
			}
			name = line[len("SHA256 ("):end]
			hexSum = line[end+len(") = "):]
		} else {
			// GNU: hex  name   (separator is two spaces, or space+asterisk)
			fields := strings.Fields(line)
			if len(fields) < 2 {
				continue
			}
			hexSum = fields[0]
			name = fields[len(fields)-1]
		}

		name = strings.TrimPrefix(strings.TrimSpace(name), "*")
		// Compare on the basename so a path prefix in the sums file still
		// matches the asset we downloaded.
		if path.Base(strings.ReplaceAll(name, "\\", "/")) != wantName {
			continue
		}

		hexSum = strings.ToLower(strings.TrimSpace(hexSum))
		if len(hexSum) != sha256.Size*2 {
			return "", fmt.Errorf("%s: malformed SHA-256 digest %q", wantName, hexSum)
		}
		if _, err := hex.DecodeString(hexSum); err != nil {
			return "", fmt.Errorf("%s: malformed SHA-256 digest %q", wantName, hexSum)
		}
		return hexSum, nil
	}
	if err := scanner.Err(); err != nil {
		return "", err
	}
	return "", fmt.Errorf("%s is not listed in %s", wantName, checksumFileName)
}

// releaseBaseURLForAsset returns the release download directory that contains
// the given artifact URL, e.g.
// "https://github.com/o/r/releases/download/v1.2.3/" for a URL ending in
// "/v1.2.3/WhatsAppDesk.exe". Deriving the base from the artifact's own URL
// guarantees the checksum is read from the same release, never a newer one.
func releaseBaseURLForAsset(assetURL string) string {
	u := strings.TrimSpace(assetURL)
	if i := strings.IndexAny(u, "?#"); i != -1 {
		u = u[:i]
	}
	u = strings.TrimSuffix(u, "/")
	if i := strings.LastIndex(u, "/"); i != -1 {
		return u[:i+1]
	}
	return u
}

// fetchChecksumFile downloads the SHA256SUMS asset from the given release URL
// base (e.g. ".../releases/download/v1.2.3/"). Returns an error when the file
// is absent, which callers treat as "no integrity data for this release".
func fetchChecksumFile(releaseBaseURL string) (string, error) {
	req, err := http.NewRequest("GET", strings.TrimSuffix(releaseBaseURL, "/")+"/"+checksumFileName, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("User-Agent", "WhatsAppDesk-Updater")

	client := &http.Client{Timeout: 45 * time.Second, Transport: checksumHTTPTransport}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("%s unavailable (HTTP %d)", checksumFileName, resp.StatusCode)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", err
	}
	return string(body), nil
}

// sha256File hashes a file on disk.
func sha256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// verifyDownloadedChecksum confirms that the file at filePath matches the
// digest published for assetName in the release's SHA256SUMS.
//
// requiresChecksum is false until the project publishes SHA256SUMS for a
// release: releases shipped before that have no integrity data, and refusing to
// update from them would strand existing installs. Once the asset exists, a
// mismatch is always fatal.
func verifyDownloadedChecksum(filePath, assetName, releaseBaseURL string, requiresChecksum bool) error {
	sums, err := fetchChecksumFile(releaseBaseURL)
	if err != nil {
		if requiresChecksum {
			return fmt.Errorf("integrity check failed: %w", err)
		}
		return nil
	}

	want, err := parseChecksumFile(sums, assetName)
	if err != nil {
		if requiresChecksum {
			return fmt.Errorf("integrity check failed: %w", err)
		}
		return nil
	}

	got, err := sha256File(filePath)
	if err != nil {
		return fmt.Errorf("integrity check failed: %w", err)
	}
	if !strings.EqualFold(got, want) {
		return errors.New("integrity check failed: downloaded file does not match the published SHA-256")
	}
	return nil
}
